### ISSUE TITLE
extract image metadata from the heic file

### ISSUE THREAD

**Issue by phanirithvij** [b1izzard-34/Dynamic-gnome-wallpapers#3]
I was able to extract the images from the heic file downloaded from https://dynamicwallpaper.club using `libheif` but I couldn't access the GPS and the timestamp metadata stored in the heic image.

After extracting the images there's no metadata in the output images. I was wondering how you were able to access it.

**Comment by phanirithvij** [comment]
@jallbrit Did you encounter this problem? You were doing something similar.

**Comment by b1izzard-34** [comment]
@phanirithvij I just added my own timestamps in the XML file manually.

**Comment by phanirithvij** [comment]
Oh. I'll post it here if I'm able to do it.

**Comment by seitbekir** [comment]
>   was able to extract the images from the heic file

@phanirithvij How you did that? share any instructions, plz.

**Comment by phanirithvij** [comment]
@seitbekir I remember doing it. I'll try posting here. But it was very hastily put together in multiple languages. I'll try to clean it up and post it here

**Comment by phanirithvij** [comment]
@seitbekir if you are familiar with swift https://github.com/mczachurski/wallpapper
